### PR TITLE
Feat: dropdown now closes when losing focus

### PR DESCRIPTION
**Pull request by gsi-kevincarrera**

### CODE REVIEW

**Comment by markteekman** [comment]
Thanks @gsi-kevincarrera, I'll review this soon!

**Review by markteekman — APPROVED** [review]

**Comment by markteekman** [comment]
Looks great @gsi-kevincarrera, thanks for the enhancement! 🙂

**Comment by gsi-kevincarrera** [comment]
Anytime :)

**Comment by markteekman** [comment]
Closing this one since it's solved in #88 🙂

**Comment by markteekman** [comment]
Reopened, see comments in #88.

**Pull request merged**
