### PR TITLE
feat: astro-font - optimize fonts & prevent CLS

### PR DESCRIPTION
**Pull request by rishi-raj-jain**

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
CLS before: 0.346 - Failing Core Web Vitals

Screenshot 2024-01-13 at 11 13 25 PM

**Comment by markteekman** [comment]
Hey @rishi-raj-jain, I see this is still on draft, let me know when you're ready for me to take a look at it. Can you also elaborate your changes and maybe explaining the advantages of your package?

Thanks!

**Comment by rishi-raj-jain** [comment]
Hey @markteekman,

the changes would basically involve using CSS variables to use personalised fallback font generated to optimise CLS & Layout Shifts of the page caused due to fonts.

>  explaining the advantages of your package?

More into how `astro-font` is built: https://www.launchfa.st/blog/building-astro-font

Basically, it optimally load web fonts with zero layout shift, thanks to the underlying CSS size-adjust property used.

**Comment by markteekman** [comment]
Sounds good @rishi-raj-jain, thanks for explaining! I'll look into the PR soon 😄

**Comment by rishi-raj-jain** [comment]
@markteekman 

Give me a day or two, and I'll get this to completion...

**Comment by philManWithBeard** [comment]
Hi Rishi, I tried to implement this on the accessible astro theme, but I still get crazy CLS.

Sorry if this is the wrong thread Mark. Let me know if I should put it elsewhere.

Screenshot 2024-03-17 at 11 12 56
https://pagespeed.web.dev/analysis/https-druidsheath-uk/p8ttssydrg?form_factor=mobile

https://github.com/philManWithBeard/grassroots-druids-heath/blob/main/src/layouts/DefaultLayout.astro
https://github.com/philManWithBeard/grassroots-druids-heath/blob/main/src/assets/scss/base/_font.scss

**Comment by markteekman** [comment]
@rishi-raj-jain I didn't notice this PR going from draft to review requested, my bad 😅 It looks good, but do you have any idea about the implications it has on performance? I like to keep the theme as clean as possible, only adding packages when it has a significant benefit.

**Comment by markteekman** [comment]
Hey @rishi-raj-jain this PR has gone a little stale. I'm working on a roadmap for some upgrades for the Accessible Astro projects and I'll put https://github.com/rishi-raj-jain/astro-font on the list there and close this PR for now 😄

**Pull request closed without merging**
