### PR TITLE
Feat/mobile menu traps focus

### PR DESCRIPTION
**Pull request by gsi-kevincarrera**
For this feature, I needed to extract the logic of the callback function of the event listener of the main menu. Then use the same logic on the mobile menu to trap the focus on it

### CODE REVIEW

**Comment by markteekman** [comment]
And this one too 🙂

**Review by markteekman — CHANGES_REQUESTED** [review]
@gsi-kevincarrera it looks good, but there's a small issue on mobile. When the dropdown is openend with enter/space, you can't tab into the dropdown, instead it skips the items entirely. I've taken a recording where I first tab to all the menu items, then use the arrow keys and lastly tab again with the menu opened where you can see the items being skipped (only by pressing the down arrow key on the button is when I can get into the menu):

https://github.com/markteekman/accessible-astro-starter/assets/3909046/8ee089f9-10b6-4fdd-842d-11e54df33ab2

Also, does this one conflict with your other PR or did you merge those changes into this one?

**Comment by gsi-kevincarrera** [comment]
Oh I see, I'll be working on it. 

The branch of the other PR came out of this one, ironically to avoid conflicts haha

**Comment by markteekman** [comment]
@gsi-kevincarrera haha ah okay, so that would mean that merging this PR after it's fixed would suffice right? 😄

**Comment by gsi-kevincarrera** [comment]
Yes 😅

**Comment by gsi-kevincarrera** [comment]
Done! :)

**Comment by markteekman** [comment]
@gsi-kevincarrera, thanks for the update! Got to testing and the arrow key down works now, however it introduces some other weird behavior, where I can tab out of the menu and it closes, but only if I do this on the last item of the menu, if I do that on any other if the items, the focus jumps to "Home" and the menu doesn't close. I also did some research on it and I don't think it's worth the trouble trying to accomplish the same keyboard navigation we have on mobile menu's (since the orientation is different anyway).

I think it's best to revert back to your other PR #87 and merge that one, leaving out the mobile improvements from this PR and just rely on the tab key in those cases 🙂

**Pull request closed without merging**
